name: Pull Request CI

on:
  pull_request:
    branches: [main, master]

jobs:
  Lint:
    uses: PolicyEngine/.github/.github/workflows/lint.yml@main
  check-changelog:
    uses: PolicyEngine/.github/.github/workflows/changelog.yml@main
